### ISSUE TITLE
Container restart fails after deployment files are garbage collected

### ISSUE THREAD

**Issue by pandemosth** [vespa-engine/vespa#26692]
What happens is that occasionally the vespa container node will be restarted due to some cluster maintenance/health reason. Sometimes when this happens the container will not restart successfully and the application has to be redeployed (i.e. using vespa deploy) in order to restore service.
I’ve been tracking this in the logs and can see something that looks odd:
The issue causing the failed restart looks to be this:
(vespa-container-0)

```
[2023-04-03 14:57:38.604] INFO    configproxy      configproxy.com.yahoo.vespa.filedistribution.FileReferenceDownloader	file 'b46a99f799a311de' not found or timed out (error code 1) at tcp/vespa-0.vespa-internal.default.svc.cluster.local:19070
```

`“b46a99f799a311de” is the application bundle. There are a few retries in the logs and eventually a full restart with backoff. This cycle repeats until the app bundle is redeployed.

There is connectivity between container and config server. On the config server side the error appears as:
```
[2023-04-03 14:57:38.603] INFO    configserver     Container.com.yahoo.vespa.config.server.filedistribution.FileServer	Failed downloading 'file 'b46a99f799a311de', client: Connection { Socket[addr=/10.96.3.4,port=52188,localport=19070] }'
```
Looking at the filesystem on the config server, /opt/vespa/var/db/vespa/filedistribution/ is empty.
This would be explained by a log entry from a few days earlier:
```
[2023-03-31 10:43:40.094] INFO    configproxy      configproxy.com.yahoo.vespa.config.proxy.filedistribution.FileReferencesAndDownloadsMaintainer	Files that can be deleted in /opt/vespa/var/db/vespa/filedistribution (not used since 2023-03-17T10:43:40.064497184Z): [b099f8e64547a6d3, b46a99f799a311de, 3bfa63fe6fb5e795, cdfb8f194d6c5d2d, 1a3342246e80853f]
```
So, it appears as if a housekeeping process is clearing out those deployment artifacts.

**Environment:**
 - Infrastructure: Kubernetes (GKE)

**Vespa version**
Vespa version: 8.131.17

**Slack thread**
https://vespatalk.slack.com/archives/C038YTM5SUQ/p1680597019763339

**Comment by pandemosth** [comment]
Note that in my particular case, and based on the GKE sample here - https://github.com/vespa-engine/sample-apps/blob/master/examples/operations/basic-search-on-gke/templates/container.yml - the container does not have persistent disk storage so any local bundle file is lost on restart and refetched from the config server.

**Comment by kkraune** [comment]
Good point! https://github.com/vespa-engine/sample-apps/tree/master/examples/operations/multinode-HA/gke is maybe more up to date, so I will look into removing basic-search-on-gke

**Comment by hmusum** [comment]
Issue fixed in 8.132.43 and missing bundle on container node was due to not having persistent storage. Closing ticket

**Comment by pandemosth** [comment]
I'm still seeing this issue in 8.153.19

```
[2023-07-18 00:41:25.300] INFO    configproxy      configproxy.com.yahoo.vespa.config.proxy.filedistribution.FileReferencesAndDownloadsMaintainer	Files that can be deleted in /opt/vespa/var/db/vespa/filedistribution (not used since 2023-06-27T00:41:25.287102619Z): [8bbe791f5e5c05bb, b099f8e64547a6d3, d3b21a1e5271b9ac, cdfb8f194d6c5d2d, 3bfa63fe6fb5e795]
```

Also confused about the persistent storage explanation. Neither gke example (basic-search-on-gke or multinode-HA/gke) has a persistent volume configured for the container node. It seems as if the intended behaviour is that the container node fetches the application bundle from the admin node rather than relying on having it on a local persistent disk at startup?

**Comment by jobergum** [comment]
The fix address the configserver deletion bug, which caused

> Sometimes when this happens the container will not restart successfully 

Which could cause containers not to get the bundles. 

The configproxy message, which is similar, should not cause containers to not start? Do you see the same problem or just a similar log message?

**Comment by pandemosth** [comment]
Same problem - bundle files are deleted by housekeeping process and if container server restarts after that it fails to get the app bundle.

**Comment by hmusum** [comment]
2 things:

1. If you want to keep bundle files longer, set VESPA_KEEP_FILE_REFERENCES_DAYS as high as you want (default value if it is unset is 30 days)
2. Even if bundle files are deleted due to age they should be downloaded when they are needed. Do you have log lines from when container is started and until container gives up starting? It would be interesting to see what actually happens here.

**Comment by pandemosth** [comment]
To be clear, this housekeeping is occurring on the admin node and it's when the container node attempts to download bundle files that the error happens.

**Comment by hmusum** [comment]
The files on the admin node should not be deleted until they are not in use anymore. 

Your log line suggests that the config proxy deleted those files. That service should usually not be running on the admin node (config server is started with `vespa-start-configserver` while other nodes are started with `vespa-start-services` and only the latter will start the config proxy). Is the config proxy running on the admin node?

**Comment by pandemosth** [comment]
Yes it is, since my setup follows the sample basic-search-on-gke where the config server is configured to run on the admin node:

https://github.com/vespa-engine/sample-apps/blob/344586b940ce7965c2c83712551f23b93d9eb868/examples/operations/basic-search-on-gke/templates/services.xml#L7-L9

And the admin node is started without any command line args:

https://github.com/vespa-engine/sample-apps/blob/344586b940ce7965c2c83712551f23b93d9eb868/examples/operations/basic-search-on-gke/deployments/master.yml#L38-L60

Which in the docker image entry point script calls both `vespa-start-configserver` and then `vespa-start-services`:

https://github.com/vespa-engine/docker-image/blob/8ed7d62c8cef9f59dc0e2159d26bd718c09eb529/include/start-container.sh#L61-L66

**Comment by hmusum** [comment]
OK, thanks very much for the follow and details!

With your setup I see what the issue is, the config proxy will remove the files even if they are in use by the config server. https://github.com/vespa-engine/vespa/pull/27871 will keep some files no matter what age they are. We might also want to make sure config proxy does not remove any files at all if config server is running on the same host.

**Comment by pandemosth** [comment]
No problem, thanks for the quick investigation on this.

So if I'm understanding correctly, the lack of persistent storage on the container node is a red herring (since the config proxy on the container node will delete the downloaded bundle files after 30 days anyway).

In which case, the immediate workaround is either
1. Set VESPA_KEEP_FILE_REFERENCES_DAYS on admin/config-server node to a large value
2. Run config server as a separate pod/host that does not run `vespa-start-services`

Is that correct?

**Comment by hmusum** [comment]
Yes, all your points above are correct.

I hope to fix this properly (no need for 1. or 2.) when I get back from vacation

**Comment by hmusum** [comment]
Fixed in https://github.com/vespa-engine/vespa/pull/27871 (Vespa 8.211.11)
