### ISSUE TITLE
Use fuzzy in a SameElement Search of a map or struct

### ISSUE THREAD

**Issue by LuisaWetzel** [vespa-engine/vespa#33238]
**Describe the bug**
I want to combine the sameElement and Fuzzy Search on a map or struct field. Trying to do so I get the response that the serializing of FuzzyItem in same_element is not implemented.

**To Reproduce**
1. Create the schema:

```
schema doc {
    document doc {
        field data type map<string, string> {
            indexing: summary
            struct-field key    { indexing: attribute }
            struct-field value  { indexing: attribute }
        }
    }
    fieldset default {
        fields: data
    }
}
```

2. Run the following Query: 

```
{
	"yql": "select * from sources doc where data contains sameElement(key contains 'some key', value contains({maxEditDistance:2}fuzzy('Some value')))",
	"tracelevel": 5
}
```

3. See error

YQL query parsed: [Invalid query: Serializing of FuzzyItem in same_element is not implemented, please report this as a bug.]
Illegal Query: FUZZY(Some value,2,0,false) value:Some value field is not a string attribute

Full Response: 

```
{
	"trace": {
		"children": [
			{
				"message": "No query profile is used"
			},
			{
				"message": "Invoking chain 'vespa' [com.yahoo.prelude.statistics.StatisticsSearcher@native -> com.yahoo.prelude.querytransform.PhrasingSearcher@vespa -> ... -> federation@native]"
			},
			{
				"children": [
					{
						"message": "YQL query parsed: [Invalid query: Serializing of FuzzyItem in same_element is not implemented, please report this as a bug.]"
					},
					{
						"message": "Federating to [text]"
					},
					{
						"message": "Ignoring fill(null): Hits are unfillable: result.hits().getFilled()=null"
					},
					{
						"message": "Query time query 'data:{key:some key value:Some value}': 2 ms"
					},
					{
						"message": "Summary fetch time query 'data:{key:some key value:Some value}': 0 ms"
					}
				]
			}
		]
	},
	"root": {
		"id": "toplevel",
		"relevance": 1.0,
		"fields": {
			"totalCount": 0
		},
		"errors": [
			{
				"code": 3,
				"summary": "Illegal query",
				"source": "text",
				"message": "FUZZY(Some value,2,0,false) value:Some value field is not a string attribute"
			}
		]
	}
}
```

**Expected behavior**
I am able to use fuzzy in the sameElement Search which performs a fuzzy search on the attribute Field of the map or struct. 

**Environment (please complete the following information):**
Dockerized vespa

**Vespa version**
Vespa version: 8.471.25

**Additional context**
this works:
```
{
	"yql": "select * from sources doc where data.value contains({maxEditDistance:2}fuzzy('Some value'))",
	"tracelevel": 3
}
```
and this works: 
```
{
	"yql": "select * from sources doc where data contains sameElement(key contains 'some key', value contains 'some value')",
	"tracelevel": 3
}
```

**Comment by bratseth** [comment]
The missing serialization is fixed in 8.473.18 which should be available later today.
Please let us know if this solves your problem.

**Comment by LuisaWetzel** [comment]
I tested it, and the serialization message is gone, but I still get the error: "FUZZY(Some Value,2,0,false) value: Some Value field is not a string attribute," even though I can use fuzzy directly on data.value.

Vespa version: 8.475.11

The same query on the same document leads to the following response:
```
{
	"trace": {
		"children": [
			{
				"message": "No query profile is used"
			},
			{
				"message": "Invoking chain 'vespa' [com.yahoo.prelude.statistics.StatisticsSearcher@native -> com.yahoo.prelude.querytransform.PhrasingSearcher@vespa -> ... -> federation@native]"
			},
			{
				"children": [
					{
						"message": "YQL query parsed: [select * from doc where data contains sameElement(key contains \"some key\", value contains fuzzy(\"Some value\"))]"
					},
					{
						"message": "Federating to [text]"
					},
					{
						"message": "Ignoring fill(null): Hits are unfillable: result.hits().getFilled()=null"
					},
					{
						"message": "Query time query 'data:{key:some key value:Some value}': 7 ms"
					},
					{
						"message": "Summary fetch time query 'data:{key:some key value:Some value}': 0 ms"
					}
				]
			}
		]
	},
	"root": {
		"id": "toplevel",
		"relevance": 1.0,
		"fields": {
			"totalCount": 0
		},
		"errors": [
			{
				"code": 3,
				"summary": "Illegal query",
				"source": "text",
				"message": "FUZZY(Some value,2,0,false) value:Some value field is not a string attribute"
			}
		]
	}
}
```

**Comment by bratseth** [comment]
Thank you, this time we (@vekterli) verified this on our side. It should work for indexed search on 8.479. Let us know if you require this for streaming.

**Comment by LuisaWetzel** [comment]
It works fine now, thank you.

**Comment by vekterli** [comment]
For reference, test was added in https://github.com/vespa-engine/system-test/pull/4345
